# Generated by Django 4.1.7 on 2023-03-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fechaDeEntrada', models.DateField()),
                ('pagado', models.BooleanField()),
            ],
        ),
        migrations.RenameModel(
            old_name='curso',
            new_name='hospedaje',
        ),
        migrations.RenameModel(
            old_name='estudiante',
            new_name='huesped',
        ),
        migrations.DeleteModel(
            name='entregable',
        ),
        migrations.RenameField(
            model_name='hospedaje',
            old_name='camada',
            new_name='HabDispo',
        ),
    ]
