# Generated by Django 4.1.7 on 2023-04-10 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reserva',
        ),
    ]
